config/routes.rb
Rails.application.routes.draw do
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_rich_text :description
  def colors
    Colors::ColorScheme.const_get(self.color_scheme)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with name: ENV["HTTP_BASIC_AUTH_USER"], password: ENV["HTTP_BASIC_AUTH_PASSWORD"], except: :index
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    uploaded_io = params[:project][:image]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    @project.image = uploaded_io.original_filename

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :tagline, :description, :vcs, :link, :technologies, :image, :color_scheme)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors/color_scheme.rb
module Colors
  module ColorScheme
    TWO_INCH_BRUSH = {
      background: "bg-green-600",
      text: "text-green-50",
      accent: "text-purple-200",
      accent_hover: "hover:text-purple-100"
    }

    SKINSMATCH = {
      background: "bg-neutral-600",
      text: "text-neutral-100",
      accent: "text-amber-400",
      accent_hover: "hover:text-amber-200"
    }

    FRYDERYK = {
      background: "bg-sky-100",
      text: "text-sky-800",
      accent: "text-sky-500",
      accent_hover: "hover:text-sky-300"
    }

    KALM_KANINE = {
      background: "bg-teal-600",
      text: "text-teal-100",
      accent: "text-yellow-300",
      accent_hover: "hover:text-yellow-500"
    }

    THIS_WEBSITE = {
      background: "bg-emerald-800",
      text: "text-emerald-100",
      accent: "text-cyan-400",
      accent_hover: "hover:text-cyan-200"
    }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Felix Auer | felixauer.com</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="apple-touch-icon" sizes="57x57" href="favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png">
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/misc/_footer.html.erb
<footer class="bg-white">
    <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
        <div class="flex justify-center space-x-6 md:order-2">
          <%= render 'misc/socials' %>
        </div>
        <div class="mt-8 md:mt-0 md:order-1">
            <p class="text-center text-base text-gray-400">&copy; <%= Time.now.year %> Felix Auer. All rights reserved.</p>
        </div>
    </div>
</footer>

app/views/misc/_hero.html.erb
<main class="lg:relative">
  <div class="mx-auto max-w-7xl w-full pt-16 pb-20 text-center lg:py-48 lg:text-left">
    <div class="px-4 lg:w-1/2 sm:px-8 xl:pr-16">
      <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl lg:text-5xl xl:text-6xl">
        <span class="block xl:inline">Welcome to</span>
        <span class="block text-amber-600 xl:inline">felixauer.com</span>
      </h1>
      <p class="mt-3 max-w-md mx-auto text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">My name is Felix Auer (as
        you've probably guessed already) and I'm a developer from Vienna, Austria.
      </p>
      <p class="mt-3 max-w-md mx-auto text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">
        You can find my CV and contact me on <a class="text-amber-600 hover:text-amber-800" href="https://www.linkedin.com/in/felix-auer-bb934115a/">LinkedIn</a>.
      </p>
      <div class="mt-10 sm:flex sm:justify-center lg:justify-start">
        <div class="flex justify-center space-x-6 md:order-2">
          <%= render 'misc/socials' %>
        </div>
      </div>
    </div>
  </div>
  <div class="relative w-full h-64 sm:h-72 md:h-96 lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2 lg:h-full">
    <img class="absolute inset-0 w-full h-full object-cover" src="/imgs/felix.jpg" alt="">
  </div>
</main>

app/views/misc/_socials.html.erb
<a href="https://www.linkedin.com/in/felix-auer-bb934115a/" class="text-gray-400 hover:text-gray-500">
  <span class="sr-only">LinkedIn</span>
  <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 512 512" aria-hidden="true">
    <path d="M186.4 142.4c0 19-15.3 34.5-34.2 34.5 -18.9 0-34.2-15.4-34.2-34.5 0-19 15.3-34.5 34.2-34.5C171.1 107.9 186.4 123.4 186.4 142.4zM181.4 201.3h-57.8V388.1h57.8V201.3zM273.8 201.3h-55.4V388.1h55.4c0 0 0-69.3 0-98 0-26.3 12.1-41.9 35.2-41.9 21.3 0 31.5 15 31.5 41.9 0 26.9 0 98 0 98h57.5c0 0 0-68.2 0-118.3 0-50-28.3-74.2-68-74.2 -39.6 0-56.3 30.9-56.3 30.9v-25.2H273.8z"/>
  </svg>
</a>

<a href="https://github.com/FelixAuer" class="text-gray-400 hover:text-gray-500">
  <span class="sr-only">GitHub</span>
  <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
    <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
  </svg>
</a>

<a href="https://gitlab.com/FelixAuer" class="text-gray-400 hover:text-gray-500">
  <span class="sr-only">GitLab</span>
  <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 380 380" aria-hidden="true">
    <path fill-rule="evenodd" d="M282.83,170.73l-.27-.69-26.14-68.22a6.81,6.81,0,0,0-2.69-3.24,7,7,0,0,0-8,.43,7,7,0,0,0-2.32,3.52l-17.65,54H154.29l-17.65-54A6.86,6.86,0,0,0,134.32,99a7,7,0,0,0-8-.43,6.87,6.87,0,0,0-2.69,3.24L97.44,170l-.26.69a48.54,48.54,0,0,0,16.1,56.1l.09.07.24.17,39.82,29.82,19.7,14.91,12,9.06a8.07,8.07,0,0,0,9.76,0l12-9.06,19.7-14.91,40.06-30,.1-.08A48.56,48.56,0,0,0,282.83,170.73Z"  clip-rule="evenodd"/>  </svg>
</a>

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :tagline, style: "display: block" %>
    <%= form.text_area :tagline %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.label :vcs, style: "display: block" %>
    <%= form.text_field :vcs %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :technologies, style: "display: block" %>
    <%= form.text_area :technologies %>
  </div>

  <div>
    <%= form.label :color_scheme, style: "display: block" %>
    <%= form.select :color_scheme, choices: ::Colors::ColorScheme.constants %>
  </div>

  <div>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_header.html.erb
<div class="bg-white">
  <div class="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8 lg:flex lg:justify-between">
    <div class="max-w-xl">
      <h2 class="text-4xl font-extrabold text-gray-900 sm:text-5xl sm:tracking-tight lg:text-6xl">Projects</h2>
      <p class="mt-5 text-xl text-gray-500">Check out a selection of my recent personal projects below.</p>
    </div>
  </div>
</div>

app/views/projects/_project.html.erb
<!-- ID <%= project.id %> -->
<div class="<%= project.colors[:background] %> overflow-hidden">
  <div class="relative max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:px-8">
    <div class="hidden lg:block bg-gray-50 absolute top-0 bottom-0 left-3/4 w-screen opacity-25"></div>
    <div class="mx-auto text-base max-w-prose lg:grid lg:grid-cols-2 lg:gap-8 lg:max-w-none">
      <div>
        <h2 class="text-base <%= project.colors[:accent] %> font-semibold tracking-wide uppercase"><%= project.tagline %></h2>
        <h3 class="mt-2 text-3xl leading-8 font-extrabold tracking-tight <%= project.colors[:text] %> sm:text-4xl"><%= project.name %></h3>
      </div>
    </div>
    <div class="mt-8 lg:grid lg:grid-cols-2 lg:gap-8">
      <div class="relative lg:row-start-1 lg:col-start-2">
        <svg class="hidden lg:block absolute top-0 right-0 -mt-20 -mr-20" width="404" height="384" fill="none" viewBox="0 0 404 384" aria-hidden="true">
          <defs>
            <pattern id="de316486-4a29-4312-bdfc-fbce2132a2c1" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
              <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor"/>
            </pattern>
          </defs>
          <rect width="404" height="384" fill="url(#de316486-4a29-4312-bdfc-fbce2132a2c1)"/>
        </svg>
        <div class="relative text-base mx-auto max-w-prose lg:max-w-none">
          <figure>
            <div class="aspect-w-12 aspect-h-7 lg:aspect-none">
              <img class="rounded-lg shadow-lg object-cover object-center" src="/uploads/<%= project.image %>" alt="<%= project.name %>" width="1184" height="1376">
            </div>
          </figure>
        </div>
      </div>
      <div class="mt-8 lg:mt-0">
        <div class="text-base max-w-prose mx-auto lg:max-w-none">
          <div class="text-lg <%= project.colors[:text] %>">
            <%= project.description %>
          </div>
        </div>
        <div class="mt-3 mx-auto text-sm">
          <a href="<%= project.link %>" class="font-medium <%= project.colors[:accent] %> <%= project.colors[:accent_hover] %>">Visit
            <span aria-hidden="true">&rarr;</span></a>
        </div>
        <div class="mt-5 prose prose-indigo <%= project.colors[:text] %> mx-auto lg:max-w-none lg:row-start-1 lg:col-start-1">
          <p>
            <%= project.technologies %>
          </p>
        </div>

        <% unless project.vcs.empty? %>
          <div class="mt-3 mx-auto text-sm">
            <a href="<%= project.vcs %>" class="font-medium  <%= project.colors[:accent] %> <%= project.colors[:accent_hover] %>">View
              Code
              <span aria-hidden="true">&rarr;</span></a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<div class="w-full">
  <%= render 'misc/hero' %>
</div>

<div class="w-full">
  <%= render 'header' %>
</div>

<div id="projects" class="space-y-8 w-full">
  <% @projects.each do |project| %>
    <div>
      <%= render project %>
    </div>
  <% end %>
</div>

<div class="w-full">
  <%= render 'misc/footer' %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="w-full flex-col">
  <div class="w-full">
    <%= render @project %>
  </div>
  <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
    <div class="bg-white overflow-hidden">
      <div class="relative max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:px-8">
        <div>
          <%= link_to "Edit this project", edit_project_path(@project) %> |
          <%= link_to "Back to projects", projects_path %>

          <%= button_to "Destroy this project", @project, method: :delete %>
        </div>
      </div>
    </div>
  </div>
</div>